services:
  db:
    image: postgres
    container_name: postgresdb
    restart: always
    ports:
      - 6000:5432
    env_file:
      - .env
    volumes:
      - pg:/var/lib/postgresql/data

  sorteiofeliz:
    container_name: sorteiofeliz
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env
volumes:
  pg:
